/*
 * Copyright 2016 Sidharth Kshatriya
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file needs to be autogenerated.
 * But this specific file is non-autogenerated for sample compilation purposes.
 */
#include "php.h"
#include "php_dontbug.h"

int dontbug_break_location(char *old_location, char* location) {
    if (0
            == strncmp(
                    "/home/abcdxyz/testd/light/vendor/composer/autoload_real.php",
                    location, 60)) {
        strncpy(old_location, location, PHP_DONTBUG_MAX_PATH_LEN);
        return ZEND_USER_OPCODE_DISPATCH;
    }
    if (0
            == strncmp(
                    "/home/abcdxyz/testd/light/docroot/core/modules/ckeditor/src/Plugin/Editor/CKEditor.php",
                    location, 87)) {
        strncpy(old_location, location, PHP_DONTBUG_MAX_PATH_LEN);
        return ZEND_USER_OPCODE_DISPATCH;
    }

    strncpy(old_location, location, PHP_DONTBUG_MAX_PATH_LEN);
    return ZEND_USER_OPCODE_DISPATCH;
}
